export const metadata = {
  title: 'detail',
  description: 'Generated by create next app',
};

// eslint-disable-next-line space-before-function-paren
const context = async () => {
  await new Promise((resolve) => setTimeout(resolve, 1000 * 10));

  return 'detail';
};

export default context;
