import type { Metadata } from 'next';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  team,
  analytics,
}: {
  data: any;
  children: React.ReactNode;
  team: React.ReactNode;
  analytics: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="light">
      <body>
        <h1>root layout</h1>
        {children}
        {team}
        {analytics}
      </body>
    </html>
  );
}
