'use client';
// import type { Metadata } from 'next';

import './globals.css';
import Link from 'next/link';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
  auth,
}: {
  data: any;
  auth: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="light">
      <body>
        <h1>root layout</h1>
        {children}
        {auth}

        <div className="p-8">
          <Link href="/login">login</Link>
        </div>
      </body>
    </html>
  );
}
