import type { Metadata } from 'next';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="light">
      <body>
        <div className="flex">
          <div>左侧</div>
          <div className="flex-1">{children}</div>
        </div>
      </body>
    </html>
  );
}
